module.exports = {
  forEach: require('tallbag-for-each'),
  fromObs: require('tallbag-from-obs'),
  fromIter: require('tallbag-from-iter'),
  fromEvent: require('tallbag-from-event'),
  fromPromise: require('tallbag-from-promise'),
  interval: require('tallbag-interval'),
  map: require('tallbag-map'),
  scan: require('tallbag-scan'),
  flatten: require('tallbag-flatten'),
  take: require('tallbag-take'),
  skip: require('tallbag-skip'),
  filter: require('tallbag-filter'),
  merge: require('tallbag-merge'),
  concat: require('tallbag-concat'),
  combine: require('tallbag-combine'),
  share: require('tallbag-share'),
  pipe: require('callbag-pipe'),
};
